// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Decision struct {
	ID               pgtype.UUID      `json:"id"`
	TenantID         pgtype.UUID      `json:"tenant_id"`
	Context          string           `json:"context"`
	Input            []byte           `json:"input"`
	MatchedRules     []pgtype.UUID    `json:"matched_rules"`
	Decision         string           `json:"decision"`
	FinalScore       *int32           `json:"final_score"`
	Reason           *string          `json:"reason"`
	ProcessedAt      pgtype.Timestamp `json:"processed_at"`
	ProcessingTimeMs int32            `json:"processing_time_ms"`
	EngineVersion    string           `json:"engine_version"`
}

type Rule struct {
	ID        pgtype.UUID      `json:"id"`
	TenantID  pgtype.UUID      `json:"tenant_id"`
	Name      string           `json:"name"`
	Context   string           `json:"context"`
	Condition string           `json:"condition"`
	Action    string           `json:"action"`
	Score     *int32           `json:"score"`
	Priority  int32            `json:"priority"`
	Enabled   bool             `json:"enabled"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
