// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (
    tenant_id, context, input, matched_rules, decision, final_score, reason, processing_time_ms
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, context, input, matched_rules, decision, final_score, reason, processed_at, processing_time_ms, engine_version
`

type CreateDecisionParams struct {
	TenantID         pgtype.UUID   `json:"tenant_id"`
	Context          string        `json:"context"`
	Input            []byte        `json:"input"`
	MatchedRules     []pgtype.UUID `json:"matched_rules"`
	Decision         string        `json:"decision"`
	FinalScore       *int32        `json:"final_score"`
	Reason           *string       `json:"reason"`
	ProcessingTimeMs int32         `json:"processing_time_ms"`
}

// Log a validation decision for audit trail.
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.TenantID,
		arg.Context,
		arg.Input,
		arg.MatchedRules,
		arg.Decision,
		arg.FinalScore,
		arg.Reason,
		arg.ProcessingTimeMs,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Context,
		&i.Input,
		&i.MatchedRules,
		&i.Decision,
		&i.FinalScore,
		&i.Reason,
		&i.ProcessedAt,
		&i.ProcessingTimeMs,
		&i.EngineVersion,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one

INSERT INTO rules (
    tenant_id, name, context, condition, action, score, priority, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at
`

type CreateRuleParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	Context   string      `json:"context"`
	Condition string      `json:"condition"`
	Action    string      `json:"action"`
	Score     *int32      `json:"score"`
	Priority  int32       `json:"priority"`
	Enabled   bool        `json:"enabled"`
}

// engines/general/queries.sql
// Create a new validation rule. Returns the created rule with generated ID.
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.TenantID,
		arg.Name,
		arg.Context,
		arg.Condition,
		arg.Action,
		arg.Score,
		arg.Priority,
		arg.Enabled,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Context,
		&i.Condition,
		&i.Action,
		&i.Score,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules 
WHERE id = $1 AND tenant_id = $2
`

type DeleteRuleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Hard delete a rule.
func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.Exec(ctx, deleteRule, arg.ID, arg.TenantID)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at FROM rules 
WHERE id = $1 AND tenant_id = $2
`

type GetRuleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

// Fetch a single rule by ID.
func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, arg.ID, arg.TenantID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Context,
		&i.Condition,
		&i.Action,
		&i.Score,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRules = `-- name: ListAllRules :many
SELECT id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at FROM rules 
WHERE tenant_id = $1 
ORDER BY context, priority DESC
`

// Admin query: Get all rules (including disabled) for a tenant.
func (q *Queries) ListAllRules(ctx context.Context, tenantID pgtype.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listAllRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Context,
			&i.Condition,
			&i.Action,
			&i.Score,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, tenant_id, context, input, matched_rules, decision, final_score, reason, processed_at, processing_time_ms, engine_version FROM decisions 
WHERE tenant_id = $1 AND context = $2
ORDER BY processed_at DESC
LIMIT $3 OFFSET $4
`

type ListDecisionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Context  string      `json:"context"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Query recent decisions for debugging/analytics.
func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisions,
		arg.TenantID,
		arg.Context,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Context,
			&i.Input,
			&i.MatchedRules,
			&i.Decision,
			&i.FinalScore,
			&i.Reason,
			&i.ProcessedAt,
			&i.ProcessingTimeMs,
			&i.EngineVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at FROM rules 
WHERE tenant_id = $1 
  AND ($2::text IS NULL OR context = $2)
ORDER BY context, priority DESC
`

type ListRulesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
}

func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Context,
			&i.Condition,
			&i.Action,
			&i.Score,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByContext = `-- name: ListRulesByContext :many
SELECT id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at FROM rules 
WHERE tenant_id = $1 
  AND context = $2 
  AND enabled = true 
ORDER BY priority DESC
`

type ListRulesByContextParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Context  string      `json:"context"`
}

// Get all active rules for a specific context, ordered by priority (highest first).
// This is the main query used during validation.
func (q *Queries) ListRulesByContext(ctx context.Context, arg ListRulesByContextParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRulesByContext, arg.TenantID, arg.Context)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Context,
			&i.Condition,
			&i.Action,
			&i.Score,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules 
SET 
    name = $3,
    context = $4,
    condition = $5,
    action = $6,
    score = $7,
    priority = $8,
    enabled = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, context, condition, action, score, priority, enabled, created_at, updated_at
`

type UpdateRuleParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	Context   string      `json:"context"`
	Condition string      `json:"condition"`
	Action    string      `json:"action"`
	Score     *int32      `json:"score"`
	Priority  int32       `json:"priority"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Context,
		arg.Condition,
		arg.Action,
		arg.Score,
		arg.Priority,
		arg.Enabled,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Context,
		&i.Condition,
		&i.Action,
		&i.Score,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
