// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Log a validation decision for audit trail.
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	// engines/general/queries.sql
	// Create a new validation rule. Returns the created rule with generated ID.
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	// Hard delete a rule.
	DeleteRule(ctx context.Context, arg DeleteRuleParams) error
	// Fetch a single rule by ID.
	GetRule(ctx context.Context, arg GetRuleParams) (Rule, error)
	// Admin query: Get all rules (including disabled) for a tenant.
	ListAllRules(ctx context.Context, tenantID pgtype.UUID) ([]Rule, error)
	// Query recent decisions for debugging/analytics.
	ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]Decision, error)
	// Get all active rules for a specific context, ordered by priority (highest first).
	// This is the main query used during validation.
	ListRulesByContext(ctx context.Context, arg ListRulesByContextParams) ([]Rule, error)
	// Modify an existing rule.
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error)
}

var _ Querier = (*Queries)(nil)
