/* tslint:disable */
/* eslint-disable */
/**
 * Asguard API
 * Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AnalyzeFaceRequest {
    /**
     * Base64-encoded image (with optional data URI prefix)
     */
    'image': string;
    /**
     * Enable quality checks (sharpness, brightness, face size)
     */
    'quality_checks'?: boolean;
}
export interface AnalyzeResponse {
    /**
     * Whether analysis succeeded
     */
    'success': boolean;
    /**
     * Whether a face was found
     */
    'face_detected': boolean;
    /**
     * 128-dimensional face embedding vector (if face detected)
     */
    'embedding'?: Array<number>;
    /**
     * Overall quality score (0-1)
     */
    'quality_score'?: number;
    /**
     * Normalized sharpness score (0-1)
     */
    'sharpness'?: number;
    /**
     * Normalized brightness score (0-1)
     */
    'brightness'?: number;
    /**
     * Face area relative to image (0-1)
     */
    'face_size_ratio'?: number;
    /**
     * List of quality warnings (e.g., \"too_dark\", \"too_blurry\")
     */
    'warnings'?: Array<string>;
    /**
     * Request processing time in milliseconds
     */
    'processing_time_ms'?: number;
    /**
     * Error message if success=false
     */
    'error'?: string;
}
export interface CompareFacesRequest {
    /**
     * Base64-encoded image (with optional data URI prefix)
     */
    'probe_image': string;
    /**
     * 128-dimensional embedding of the reference face
     */
    'reference_embedding': Array<number>;
    /**
     * Distance threshold for matching (lower = stricter)
     */
    'threshold'?: number;
}
export interface CompareResponse {
    'success': boolean;
    /**
     * Whether faces match (distance < threshold_used)
     */
    'match': boolean;
    /**
     * Match confidence score (0-1)
     */
    'confidence': number;
    /**
     * Euclidean distance between embeddings
     */
    'distance': number;
    /**
     * The distance threshold used for this comparison
     */
    'threshold_used': number;
    /**
     * Quality score of the probe image (0-1)
     */
    'probe_quality'?: number;
    'processing_time_ms'?: number;
    'error'?: string;
}
export interface ErrorResponse {
    'error': string;
    /**
     * Machine-readable error code
     */
    'code'?: string;
    /**
     * Additional error context
     */
    'details'?: object;
}
export interface FraudCheckRequest {
    /**
     * Unique transaction identifier
     */
    'transaction_id': string;
    /**
     * Transaction amount
     */
    'amount': number;
    /**
     * ISO 4217 currency code (USD, EUR, etc.)
     */
    'currency': string;
    /**
     * Customer identifier
     */
    'user_id': string;
    /**
     * Device fingerprint
     */
    'device_id'?: string;
    /**
     * Customer IP address
     */
    'ip_address'?: string;
    /**
     * Geo location (city, country)
     */
    'location'?: string;
    /**
     * Transaction timestamp
     */
    'timestamp'?: string;
}
export interface FraudCheckResponse {
    'transaction_id': string;
    'risk_score': number;
    'risk_level': FraudCheckResponseRiskLevelEnum;
    'reasons'?: Array<string>;
    'ai_triggered'?: boolean;
    'ai_confidence'?: number;
    'ai_recommendation'?: string;
    'ai_fraud_probability'?: number;
    'ai_summary'?: string;
    'message'?: string;
    /**
     * Request processing time in milliseconds
     */
    'processing_time_ms'?: number;
}

export const FraudCheckResponseRiskLevelEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;

export type FraudCheckResponseRiskLevelEnum = typeof FraudCheckResponseRiskLevelEnum[keyof typeof FraudCheckResponseRiskLevelEnum];

export interface HealthResponse {
    'status': HealthResponseStatusEnum;
    /**
     * Whether ML models are loaded (relevant for face service)
     */
    'models_loaded'?: boolean;
    'version'?: string;
}

export const HealthResponseStatusEnum = {
    Healthy: 'healthy',
    Unhealthy: 'unhealthy',
    Loading: 'loading'
} as const;

export type HealthResponseStatusEnum = typeof HealthResponseStatusEnum[keyof typeof HealthResponseStatusEnum];


/**
 * FaceVerificationApi - axios parameter creator
 */
export const FaceVerificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Analyze face image quality and extract embedding
         * @param {AnalyzeFaceRequest} analyzeFaceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyzeFace: async (analyzeFaceRequest: AnalyzeFaceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'analyzeFaceRequest' is not null or undefined
            assertParamExists('analyzeFace', 'analyzeFaceRequest', analyzeFaceRequest)
            const localVarPath = `/v1/analyze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(analyzeFaceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Compare a probe face image with a reference embedding
         * @param {CompareFacesRequest} compareFacesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        compareFaces: async (compareFacesRequest: CompareFacesRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'compareFacesRequest' is not null or undefined
            assertParamExists('compareFaces', 'compareFacesRequest', compareFacesRequest)
            const localVarPath = `/v1/compare`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(compareFacesRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FaceVerificationApi - functional programming interface
 */
export const FaceVerificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FaceVerificationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Analyze face image quality and extract embedding
         * @param {AnalyzeFaceRequest} analyzeFaceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async analyzeFace(analyzeFaceRequest: AnalyzeFaceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnalyzeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.analyzeFace(analyzeFaceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FaceVerificationApi.analyzeFace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Compare a probe face image with a reference embedding
         * @param {CompareFacesRequest} compareFacesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async compareFaces(compareFacesRequest: CompareFacesRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompareResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.compareFaces(compareFacesRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FaceVerificationApi.compareFaces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FaceVerificationApi - factory interface
 */
export const FaceVerificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FaceVerificationApiFp(configuration)
    return {
        /**
         * 
         * @summary Analyze face image quality and extract embedding
         * @param {AnalyzeFaceRequest} analyzeFaceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyzeFace(analyzeFaceRequest: AnalyzeFaceRequest, options?: RawAxiosRequestConfig): AxiosPromise<AnalyzeResponse> {
            return localVarFp.analyzeFace(analyzeFaceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Compare a probe face image with a reference embedding
         * @param {CompareFacesRequest} compareFacesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        compareFaces(compareFacesRequest: CompareFacesRequest, options?: RawAxiosRequestConfig): AxiosPromise<CompareResponse> {
            return localVarFp.compareFaces(compareFacesRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FaceVerificationApi - object-oriented interface
 */
export class FaceVerificationApi extends BaseAPI {
    /**
     * 
     * @summary Analyze face image quality and extract embedding
     * @param {AnalyzeFaceRequest} analyzeFaceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public analyzeFace(analyzeFaceRequest: AnalyzeFaceRequest, options?: RawAxiosRequestConfig) {
        return FaceVerificationApiFp(this.configuration).analyzeFace(analyzeFaceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Compare a probe face image with a reference embedding
     * @param {CompareFacesRequest} compareFacesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public compareFaces(compareFacesRequest: CompareFacesRequest, options?: RawAxiosRequestConfig) {
        return FaceVerificationApiFp(this.configuration).compareFaces(compareFacesRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FraudDetectionApi - axios parameter creator
 */
export const FraudDetectionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check transaction for fraud risk
         * @param {FraudCheckRequest} fraudCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkFraud: async (fraudCheckRequest: FraudCheckRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'fraudCheckRequest' is not null or undefined
            assertParamExists('checkFraud', 'fraudCheckRequest', fraudCheckRequest)
            const localVarPath = `/analyze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fraudCheckRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FraudDetectionApi - functional programming interface
 */
export const FraudDetectionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FraudDetectionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Check transaction for fraud risk
         * @param {FraudCheckRequest} fraudCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkFraud(fraudCheckRequest: FraudCheckRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FraudCheckResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkFraud(fraudCheckRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FraudDetectionApi.checkFraud']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FraudDetectionApi - factory interface
 */
export const FraudDetectionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FraudDetectionApiFp(configuration)
    return {
        /**
         * 
         * @summary Check transaction for fraud risk
         * @param {FraudCheckRequest} fraudCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkFraud(fraudCheckRequest: FraudCheckRequest, options?: RawAxiosRequestConfig): AxiosPromise<FraudCheckResponse> {
            return localVarFp.checkFraud(fraudCheckRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FraudDetectionApi - object-oriented interface
 */
export class FraudDetectionApi extends BaseAPI {
    /**
     * 
     * @summary Check transaction for fraud risk
     * @param {FraudCheckRequest} fraudCheckRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public checkFraud(fraudCheckRequest: FraudCheckRequest, options?: RawAxiosRequestConfig) {
        return FraudDetectionApiFp(this.configuration).checkFraud(fraudCheckRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemApi - axios parameter creator
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Face service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckFace: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/face/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fraud service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckFraud: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fraud/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Face service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckFace(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckFace(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.healthCheckFace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fraud service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckFraud(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckFraud(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.healthCheckFraud']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * 
         * @summary Face service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckFace(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthCheckFace(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fraud service health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckFraud(options?: RawAxiosRequestConfig): AxiosPromise<HealthResponse> {
            return localVarFp.healthCheckFraud(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemApi - object-oriented interface
 */
export class SystemApi extends BaseAPI {
    /**
     * 
     * @summary Face service health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheckFace(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).healthCheckFace(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fraud service health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheckFraud(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).healthCheckFraud(options).then((request) => request(this.axios, this.basePath));
    }
}



