# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.api.face_verification_api import FaceVerificationApi


class TestFaceVerificationApi(unittest.TestCase):
    """FaceVerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FaceVerificationApi()

    def tearDown(self) -> None:
        pass

    def test_analyze_face(self) -> None:
        """Test case for analyze_face

        Analyze face image quality and extract embedding
        """
        pass

    def test_compare_faces(self) -> None:
        """Test case for compare_faces

        Compare a probe face image with a reference embedding
        """
        pass


if __name__ == '__main__':
    unittest.main()
