# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.api.fraud_detection_api import FraudDetectionApi


class TestFraudDetectionApi(unittest.TestCase):
    """FraudDetectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FraudDetectionApi()

    def tearDown(self) -> None:
        pass

    def test_check_fraud(self) -> None:
        """Test case for check_fraud

        Check transaction for fraud risk
        """
        pass


if __name__ == '__main__':
    unittest.main()
