# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.models.analyze_response import AnalyzeResponse

class TestAnalyzeResponse(unittest.TestCase):
    """AnalyzeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyzeResponse:
        """Test AnalyzeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyzeResponse`
        """
        model = AnalyzeResponse()
        if include_optional:
            return AnalyzeResponse(
                success = True,
                face_detected = True,
                embedding = [
                    1.337
                    ],
                quality_score = 1.337,
                sharpness = 1.337,
                brightness = 1.337,
                face_size_ratio = 1.337,
                warnings = [
                    ''
                    ],
                processing_time_ms = 56,
                error = ''
            )
        else:
            return AnalyzeResponse(
                success = True,
                face_detected = True,
        )
        """

    def testAnalyzeResponse(self):
        """Test AnalyzeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
