# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.api.system_api import SystemApi


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SystemApi()

    def tearDown(self) -> None:
        pass

    def test_health_check_face(self) -> None:
        """Test case for health_check_face

        Face service health check
        """
        pass

    def test_health_check_fraud(self) -> None:
        """Test case for health_check_fraud

        Fraud service health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
