# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.models.compare_response import CompareResponse

class TestCompareResponse(unittest.TestCase):
    """CompareResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompareResponse:
        """Test CompareResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompareResponse`
        """
        model = CompareResponse()
        if include_optional:
            return CompareResponse(
                success = True,
                match = True,
                confidence = 0,
                distance = 1.337,
                threshold_used = 1.337,
                probe_quality = 1.337,
                processing_time_ms = 56,
                error = ''
            )
        else:
            return CompareResponse(
                success = True,
                match = True,
                confidence = 0,
                distance = 1.337,
                threshold_used = 1.337,
        )
        """

    def testCompareResponse(self):
        """Test CompareResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
