# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.models.fraud_check_response import FraudCheckResponse

class TestFraudCheckResponse(unittest.TestCase):
    """FraudCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FraudCheckResponse:
        """Test FraudCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FraudCheckResponse`
        """
        model = FraudCheckResponse()
        if include_optional:
            return FraudCheckResponse(
                transaction_id = '',
                risk_score = 1.337,
                risk_level = 'LOW',
                reasons = [
                    ''
                    ],
                ai_triggered = True,
                ai_confidence = 1.337,
                ai_recommendation = '',
                ai_fraud_probability = 1.337,
                ai_summary = '',
                message = '',
                processing_time_ms = 56
            )
        else:
            return FraudCheckResponse(
                transaction_id = '',
                risk_score = 1.337,
                risk_level = 'LOW',
        )
        """

    def testFraudCheckResponse(self):
        """Test FraudCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
