# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from asguard.models.compare_faces_request import CompareFacesRequest

class TestCompareFacesRequest(unittest.TestCase):
    """CompareFacesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompareFacesRequest:
        """Test CompareFacesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompareFacesRequest`
        """
        model = CompareFacesRequest()
        if include_optional:
            return CompareFacesRequest(
                probe_image = '',
                reference_embedding = [
                    1.337
                    ],
                threshold = 1.337
            )
        else:
            return CompareFacesRequest(
                probe_image = '',
                reference_embedding = [
                    1.337
                    ],
        )
        """

    def testCompareFacesRequest(self):
        """Test CompareFacesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
