# coding: utf-8

# flake8: noqa
"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from asguard.models.analyze_face_request import AnalyzeFaceRequest
from asguard.models.analyze_response import AnalyzeResponse
from asguard.models.compare_faces_request import CompareFacesRequest
from asguard.models.compare_response import CompareResponse
from asguard.models.error_response import ErrorResponse
from asguard.models.fraud_check_request import FraudCheckRequest
from asguard.models.fraud_check_response import FraudCheckResponse
from asguard.models.health_response import HealthResponse

