# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class AnalyzeResponse(BaseModel):
    """
    AnalyzeResponse
    """ # noqa: E501
    success: StrictBool = Field(description="Whether analysis succeeded")
    face_detected: StrictBool = Field(description="Whether a face was found")
    embedding: Optional[Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=128, max_length=128)]] = Field(default=None, description="128-dimensional face embedding vector (if face detected)")
    quality_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Overall quality score (0-1)")
    sharpness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Normalized sharpness score (0-1)")
    brightness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Normalized brightness score (0-1)")
    face_size_ratio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Face area relative to image (0-1)")
    warnings: Optional[List[StrictStr]] = Field(default=None, description="List of quality warnings (e.g., \"too_dark\", \"too_blurry\")")
    processing_time_ms: Optional[StrictInt] = Field(default=None, description="Request processing time in milliseconds")
    error: Optional[StrictStr] = Field(default=None, description="Error message if success=false")
    __properties: ClassVar[List[str]] = ["success", "face_detected", "embedding", "quality_score", "sharpness", "brightness", "face_size_ratio", "warnings", "processing_time_ms", "error"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnalyzeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnalyzeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "face_detected": obj.get("face_detected"),
            "embedding": obj.get("embedding"),
            "quality_score": obj.get("quality_score"),
            "sharpness": obj.get("sharpness"),
            "brightness": obj.get("brightness"),
            "face_size_ratio": obj.get("face_size_ratio"),
            "warnings": obj.get("warnings"),
            "processing_time_ms": obj.get("processing_time_ms"),
            "error": obj.get("error")
        })
        return _obj


