# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CompareResponse(BaseModel):
    """
    CompareResponse
    """ # noqa: E501
    success: StrictBool
    match: StrictBool = Field(description="Whether faces match (distance < threshold_used)")
    confidence: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Match confidence score (0-1)")
    distance: Union[StrictFloat, StrictInt] = Field(description="Euclidean distance between embeddings")
    threshold_used: Union[StrictFloat, StrictInt] = Field(description="The distance threshold used for this comparison")
    probe_quality: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Quality score of the probe image (0-1)")
    processing_time_ms: Optional[StrictInt] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "match", "confidence", "distance", "threshold_used", "probe_quality", "processing_time_ms", "error"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompareResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompareResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "match": obj.get("match"),
            "confidence": obj.get("confidence"),
            "distance": obj.get("distance"),
            "threshold_used": obj.get("threshold_used"),
            "probe_quality": obj.get("probe_quality"),
            "processing_time_ms": obj.get("processing_time_ms"),
            "error": obj.get("error")
        })
        return _obj


