# coding: utf-8

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class FraudCheckResponse(BaseModel):
    """
    FraudCheckResponse
    """ # noqa: E501
    transaction_id: StrictStr
    risk_score: Union[StrictFloat, StrictInt]
    risk_level: StrictStr
    reasons: Optional[List[StrictStr]] = None
    ai_triggered: Optional[StrictBool] = None
    ai_confidence: Optional[Union[StrictFloat, StrictInt]] = None
    ai_recommendation: Optional[StrictStr] = None
    ai_fraud_probability: Optional[Union[StrictFloat, StrictInt]] = None
    ai_summary: Optional[StrictStr] = None
    message: Optional[StrictStr] = None
    processing_time_ms: Optional[StrictInt] = Field(default=None, description="Request processing time in milliseconds")
    __properties: ClassVar[List[str]] = ["transaction_id", "risk_score", "risk_level", "reasons", "ai_triggered", "ai_confidence", "ai_recommendation", "ai_fraud_probability", "ai_summary", "message", "processing_time_ms"]

    @field_validator('risk_level')
    def risk_level_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']):
            raise ValueError("must be one of enum values ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FraudCheckResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FraudCheckResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "transaction_id": obj.get("transaction_id"),
            "risk_score": obj.get("risk_score"),
            "risk_level": obj.get("risk_level"),
            "reasons": obj.get("reasons"),
            "ai_triggered": obj.get("ai_triggered"),
            "ai_confidence": obj.get("ai_confidence"),
            "ai_recommendation": obj.get("ai_recommendation"),
            "ai_fraud_probability": obj.get("ai_fraud_probability"),
            "ai_summary": obj.get("ai_summary"),
            "message": obj.get("message"),
            "processing_time_ms": obj.get("processing_time_ms")
        })
        return _obj


