# coding: utf-8

# flake8: noqa

"""
    Asguard API

    Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "FaceVerificationApi",
    "FraudDetectionApi",
    "SystemApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnalyzeFaceRequest",
    "AnalyzeResponse",
    "CompareFacesRequest",
    "CompareResponse",
    "ErrorResponse",
    "FraudCheckRequest",
    "FraudCheckResponse",
    "HealthResponse",
]

# import apis into sdk package
from asguard.api.face_verification_api import FaceVerificationApi as FaceVerificationApi
from asguard.api.fraud_detection_api import FraudDetectionApi as FraudDetectionApi
from asguard.api.system_api import SystemApi as SystemApi

# import ApiClient
from asguard.api_response import ApiResponse as ApiResponse
from asguard.api_client import ApiClient as ApiClient
from asguard.configuration import Configuration as Configuration
from asguard.exceptions import OpenApiException as OpenApiException
from asguard.exceptions import ApiTypeError as ApiTypeError
from asguard.exceptions import ApiValueError as ApiValueError
from asguard.exceptions import ApiKeyError as ApiKeyError
from asguard.exceptions import ApiAttributeError as ApiAttributeError
from asguard.exceptions import ApiException as ApiException

# import models into sdk package
from asguard.models.analyze_face_request import AnalyzeFaceRequest as AnalyzeFaceRequest
from asguard.models.analyze_response import AnalyzeResponse as AnalyzeResponse
from asguard.models.compare_faces_request import CompareFacesRequest as CompareFacesRequest
from asguard.models.compare_response import CompareResponse as CompareResponse
from asguard.models.error_response import ErrorResponse as ErrorResponse
from asguard.models.fraud_check_request import FraudCheckRequest as FraudCheckRequest
from asguard.models.fraud_check_response import FraudCheckResponse as FraudCheckResponse
from asguard.models.health_response import HealthResponse as HealthResponse

