/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompareFacesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompareFacesRequest{}

// CompareFacesRequest struct for CompareFacesRequest
type CompareFacesRequest struct {
	// Base64-encoded image (with optional data URI prefix)
	ProbeImage string `json:"probe_image"`
	// 128-dimensional embedding of the reference face
	ReferenceEmbedding []float32 `json:"reference_embedding"`
	// Distance threshold for matching (lower = stricter)
	Threshold *float32 `json:"threshold,omitempty"`
}

type _CompareFacesRequest CompareFacesRequest

// NewCompareFacesRequest instantiates a new CompareFacesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompareFacesRequest(probeImage string, referenceEmbedding []float32) *CompareFacesRequest {
	this := CompareFacesRequest{}
	this.ProbeImage = probeImage
	this.ReferenceEmbedding = referenceEmbedding
	var threshold float32 = 0.6
	this.Threshold = &threshold
	return &this
}

// NewCompareFacesRequestWithDefaults instantiates a new CompareFacesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompareFacesRequestWithDefaults() *CompareFacesRequest {
	this := CompareFacesRequest{}
	var threshold float32 = 0.6
	this.Threshold = &threshold
	return &this
}

// GetProbeImage returns the ProbeImage field value
func (o *CompareFacesRequest) GetProbeImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProbeImage
}

// GetProbeImageOk returns a tuple with the ProbeImage field value
// and a boolean to check if the value has been set.
func (o *CompareFacesRequest) GetProbeImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProbeImage, true
}

// SetProbeImage sets field value
func (o *CompareFacesRequest) SetProbeImage(v string) {
	o.ProbeImage = v
}

// GetReferenceEmbedding returns the ReferenceEmbedding field value
func (o *CompareFacesRequest) GetReferenceEmbedding() []float32 {
	if o == nil {
		var ret []float32
		return ret
	}

	return o.ReferenceEmbedding
}

// GetReferenceEmbeddingOk returns a tuple with the ReferenceEmbedding field value
// and a boolean to check if the value has been set.
func (o *CompareFacesRequest) GetReferenceEmbeddingOk() ([]float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceEmbedding, true
}

// SetReferenceEmbedding sets field value
func (o *CompareFacesRequest) SetReferenceEmbedding(v []float32) {
	o.ReferenceEmbedding = v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *CompareFacesRequest) GetThreshold() float32 {
	if o == nil || IsNil(o.Threshold) {
		var ret float32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompareFacesRequest) GetThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *CompareFacesRequest) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given float32 and assigns it to the Threshold field.
func (o *CompareFacesRequest) SetThreshold(v float32) {
	o.Threshold = &v
}

func (o CompareFacesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompareFacesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["probe_image"] = o.ProbeImage
	toSerialize["reference_embedding"] = o.ReferenceEmbedding
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	return toSerialize, nil
}

func (o *CompareFacesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"probe_image",
		"reference_embedding",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompareFacesRequest := _CompareFacesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompareFacesRequest)

	if err != nil {
		return err
	}

	*o = CompareFacesRequest(varCompareFacesRequest)

	return err
}

type NullableCompareFacesRequest struct {
	value *CompareFacesRequest
	isSet bool
}

func (v NullableCompareFacesRequest) Get() *CompareFacesRequest {
	return v.value
}

func (v *NullableCompareFacesRequest) Set(val *CompareFacesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompareFacesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompareFacesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompareFacesRequest(val *CompareFacesRequest) *NullableCompareFacesRequest {
	return &NullableCompareFacesRequest{value: val, isSet: true}
}

func (v NullableCompareFacesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompareFacesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


