/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FraudCheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FraudCheckRequest{}

// FraudCheckRequest struct for FraudCheckRequest
type FraudCheckRequest struct {
	// Unique transaction identifier
	TransactionId string `json:"transaction_id"`
	// Transaction amount
	Amount float32 `json:"amount"`
	// ISO 4217 currency code (USD, EUR, etc.)
	Currency string `json:"currency"`
	// Customer identifier
	UserId string `json:"user_id"`
	// Device fingerprint
	DeviceId *string `json:"device_id,omitempty"`
	// Customer IP address
	IpAddress *string `json:"ip_address,omitempty"`
	// Geo location (city, country)
	Location *string `json:"location,omitempty"`
	// Transaction timestamp
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

type _FraudCheckRequest FraudCheckRequest

// NewFraudCheckRequest instantiates a new FraudCheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFraudCheckRequest(transactionId string, amount float32, currency string, userId string) *FraudCheckRequest {
	this := FraudCheckRequest{}
	this.TransactionId = transactionId
	this.Amount = amount
	this.Currency = currency
	this.UserId = userId
	return &this
}

// NewFraudCheckRequestWithDefaults instantiates a new FraudCheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFraudCheckRequestWithDefaults() *FraudCheckRequest {
	this := FraudCheckRequest{}
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *FraudCheckRequest) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *FraudCheckRequest) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetAmount returns the Amount field value
func (o *FraudCheckRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *FraudCheckRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetCurrency returns the Currency field value
func (o *FraudCheckRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *FraudCheckRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetUserId returns the UserId field value
func (o *FraudCheckRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *FraudCheckRequest) SetUserId(v string) {
	o.UserId = v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *FraudCheckRequest) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *FraudCheckRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *FraudCheckRequest) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *FraudCheckRequest) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *FraudCheckRequest) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *FraudCheckRequest) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *FraudCheckRequest) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *FraudCheckRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *FraudCheckRequest) SetLocation(v string) {
	o.Location = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *FraudCheckRequest) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckRequest) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *FraudCheckRequest) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *FraudCheckRequest) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o FraudCheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FraudCheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["amount"] = o.Amount
	toSerialize["currency"] = o.Currency
	toSerialize["user_id"] = o.UserId
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

func (o *FraudCheckRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_id",
		"amount",
		"currency",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFraudCheckRequest := _FraudCheckRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFraudCheckRequest)

	if err != nil {
		return err
	}

	*o = FraudCheckRequest(varFraudCheckRequest)

	return err
}

type NullableFraudCheckRequest struct {
	value *FraudCheckRequest
	isSet bool
}

func (v NullableFraudCheckRequest) Get() *FraudCheckRequest {
	return v.value
}

func (v *NullableFraudCheckRequest) Set(val *FraudCheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFraudCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFraudCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFraudCheckRequest(val *FraudCheckRequest) *NullableFraudCheckRequest {
	return &NullableFraudCheckRequest{value: val, isSet: true}
}

func (v NullableFraudCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFraudCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


