/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalyzeFaceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyzeFaceRequest{}

// AnalyzeFaceRequest struct for AnalyzeFaceRequest
type AnalyzeFaceRequest struct {
	// Base64-encoded image (with optional data URI prefix)
	Image string `json:"image"`
	// Enable quality checks (sharpness, brightness, face size)
	QualityChecks *bool `json:"quality_checks,omitempty"`
}

type _AnalyzeFaceRequest AnalyzeFaceRequest

// NewAnalyzeFaceRequest instantiates a new AnalyzeFaceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyzeFaceRequest(image string) *AnalyzeFaceRequest {
	this := AnalyzeFaceRequest{}
	this.Image = image
	var qualityChecks bool = false
	this.QualityChecks = &qualityChecks
	return &this
}

// NewAnalyzeFaceRequestWithDefaults instantiates a new AnalyzeFaceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyzeFaceRequestWithDefaults() *AnalyzeFaceRequest {
	this := AnalyzeFaceRequest{}
	var qualityChecks bool = false
	this.QualityChecks = &qualityChecks
	return &this
}

// GetImage returns the Image field value
func (o *AnalyzeFaceRequest) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *AnalyzeFaceRequest) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *AnalyzeFaceRequest) SetImage(v string) {
	o.Image = v
}

// GetQualityChecks returns the QualityChecks field value if set, zero value otherwise.
func (o *AnalyzeFaceRequest) GetQualityChecks() bool {
	if o == nil || IsNil(o.QualityChecks) {
		var ret bool
		return ret
	}
	return *o.QualityChecks
}

// GetQualityChecksOk returns a tuple with the QualityChecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeFaceRequest) GetQualityChecksOk() (*bool, bool) {
	if o == nil || IsNil(o.QualityChecks) {
		return nil, false
	}
	return o.QualityChecks, true
}

// HasQualityChecks returns a boolean if a field has been set.
func (o *AnalyzeFaceRequest) HasQualityChecks() bool {
	if o != nil && !IsNil(o.QualityChecks) {
		return true
	}

	return false
}

// SetQualityChecks gets a reference to the given bool and assigns it to the QualityChecks field.
func (o *AnalyzeFaceRequest) SetQualityChecks(v bool) {
	o.QualityChecks = &v
}

func (o AnalyzeFaceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyzeFaceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image
	if !IsNil(o.QualityChecks) {
		toSerialize["quality_checks"] = o.QualityChecks
	}
	return toSerialize, nil
}

func (o *AnalyzeFaceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyzeFaceRequest := _AnalyzeFaceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyzeFaceRequest)

	if err != nil {
		return err
	}

	*o = AnalyzeFaceRequest(varAnalyzeFaceRequest)

	return err
}

type NullableAnalyzeFaceRequest struct {
	value *AnalyzeFaceRequest
	isSet bool
}

func (v NullableAnalyzeFaceRequest) Get() *AnalyzeFaceRequest {
	return v.value
}

func (v *NullableAnalyzeFaceRequest) Set(val *AnalyzeFaceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyzeFaceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyzeFaceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyzeFaceRequest(val *AnalyzeFaceRequest) *NullableAnalyzeFaceRequest {
	return &NullableAnalyzeFaceRequest{value: val, isSet: true}
}

func (v NullableAnalyzeFaceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyzeFaceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


