/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FraudCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FraudCheckResponse{}

// FraudCheckResponse struct for FraudCheckResponse
type FraudCheckResponse struct {
	TransactionId string `json:"transaction_id"`
	RiskScore float32 `json:"risk_score"`
	RiskLevel string `json:"risk_level"`
	Reasons []string `json:"reasons,omitempty"`
	AiTriggered *bool `json:"ai_triggered,omitempty"`
	AiConfidence *float32 `json:"ai_confidence,omitempty"`
	AiRecommendation *string `json:"ai_recommendation,omitempty"`
	AiFraudProbability *float32 `json:"ai_fraud_probability,omitempty"`
	AiSummary *string `json:"ai_summary,omitempty"`
	Message *string `json:"message,omitempty"`
	// Request processing time in milliseconds
	ProcessingTimeMs *int32 `json:"processing_time_ms,omitempty"`
}

type _FraudCheckResponse FraudCheckResponse

// NewFraudCheckResponse instantiates a new FraudCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFraudCheckResponse(transactionId string, riskScore float32, riskLevel string) *FraudCheckResponse {
	this := FraudCheckResponse{}
	this.TransactionId = transactionId
	this.RiskScore = riskScore
	this.RiskLevel = riskLevel
	return &this
}

// NewFraudCheckResponseWithDefaults instantiates a new FraudCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFraudCheckResponseWithDefaults() *FraudCheckResponse {
	this := FraudCheckResponse{}
	return &this
}

// GetTransactionId returns the TransactionId field value
func (o *FraudCheckResponse) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *FraudCheckResponse) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetRiskScore returns the RiskScore field value
func (o *FraudCheckResponse) GetRiskScore() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RiskScore
}

// GetRiskScoreOk returns a tuple with the RiskScore field value
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskScore, true
}

// SetRiskScore sets field value
func (o *FraudCheckResponse) SetRiskScore(v float32) {
	o.RiskScore = v
}

// GetRiskLevel returns the RiskLevel field value
func (o *FraudCheckResponse) GetRiskLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RiskLevel
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetRiskLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskLevel, true
}

// SetRiskLevel sets field value
func (o *FraudCheckResponse) SetRiskLevel(v string) {
	o.RiskLevel = v
}

// GetReasons returns the Reasons field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetReasons() []string {
	if o == nil || IsNil(o.Reasons) {
		var ret []string
		return ret
	}
	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetReasonsOk() ([]string, bool) {
	if o == nil || IsNil(o.Reasons) {
		return nil, false
	}
	return o.Reasons, true
}

// HasReasons returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasReasons() bool {
	if o != nil && !IsNil(o.Reasons) {
		return true
	}

	return false
}

// SetReasons gets a reference to the given []string and assigns it to the Reasons field.
func (o *FraudCheckResponse) SetReasons(v []string) {
	o.Reasons = v
}

// GetAiTriggered returns the AiTriggered field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetAiTriggered() bool {
	if o == nil || IsNil(o.AiTriggered) {
		var ret bool
		return ret
	}
	return *o.AiTriggered
}

// GetAiTriggeredOk returns a tuple with the AiTriggered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetAiTriggeredOk() (*bool, bool) {
	if o == nil || IsNil(o.AiTriggered) {
		return nil, false
	}
	return o.AiTriggered, true
}

// HasAiTriggered returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasAiTriggered() bool {
	if o != nil && !IsNil(o.AiTriggered) {
		return true
	}

	return false
}

// SetAiTriggered gets a reference to the given bool and assigns it to the AiTriggered field.
func (o *FraudCheckResponse) SetAiTriggered(v bool) {
	o.AiTriggered = &v
}

// GetAiConfidence returns the AiConfidence field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetAiConfidence() float32 {
	if o == nil || IsNil(o.AiConfidence) {
		var ret float32
		return ret
	}
	return *o.AiConfidence
}

// GetAiConfidenceOk returns a tuple with the AiConfidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetAiConfidenceOk() (*float32, bool) {
	if o == nil || IsNil(o.AiConfidence) {
		return nil, false
	}
	return o.AiConfidence, true
}

// HasAiConfidence returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasAiConfidence() bool {
	if o != nil && !IsNil(o.AiConfidence) {
		return true
	}

	return false
}

// SetAiConfidence gets a reference to the given float32 and assigns it to the AiConfidence field.
func (o *FraudCheckResponse) SetAiConfidence(v float32) {
	o.AiConfidence = &v
}

// GetAiRecommendation returns the AiRecommendation field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetAiRecommendation() string {
	if o == nil || IsNil(o.AiRecommendation) {
		var ret string
		return ret
	}
	return *o.AiRecommendation
}

// GetAiRecommendationOk returns a tuple with the AiRecommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetAiRecommendationOk() (*string, bool) {
	if o == nil || IsNil(o.AiRecommendation) {
		return nil, false
	}
	return o.AiRecommendation, true
}

// HasAiRecommendation returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasAiRecommendation() bool {
	if o != nil && !IsNil(o.AiRecommendation) {
		return true
	}

	return false
}

// SetAiRecommendation gets a reference to the given string and assigns it to the AiRecommendation field.
func (o *FraudCheckResponse) SetAiRecommendation(v string) {
	o.AiRecommendation = &v
}

// GetAiFraudProbability returns the AiFraudProbability field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetAiFraudProbability() float32 {
	if o == nil || IsNil(o.AiFraudProbability) {
		var ret float32
		return ret
	}
	return *o.AiFraudProbability
}

// GetAiFraudProbabilityOk returns a tuple with the AiFraudProbability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetAiFraudProbabilityOk() (*float32, bool) {
	if o == nil || IsNil(o.AiFraudProbability) {
		return nil, false
	}
	return o.AiFraudProbability, true
}

// HasAiFraudProbability returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasAiFraudProbability() bool {
	if o != nil && !IsNil(o.AiFraudProbability) {
		return true
	}

	return false
}

// SetAiFraudProbability gets a reference to the given float32 and assigns it to the AiFraudProbability field.
func (o *FraudCheckResponse) SetAiFraudProbability(v float32) {
	o.AiFraudProbability = &v
}

// GetAiSummary returns the AiSummary field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetAiSummary() string {
	if o == nil || IsNil(o.AiSummary) {
		var ret string
		return ret
	}
	return *o.AiSummary
}

// GetAiSummaryOk returns a tuple with the AiSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetAiSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.AiSummary) {
		return nil, false
	}
	return o.AiSummary, true
}

// HasAiSummary returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasAiSummary() bool {
	if o != nil && !IsNil(o.AiSummary) {
		return true
	}

	return false
}

// SetAiSummary gets a reference to the given string and assigns it to the AiSummary field.
func (o *FraudCheckResponse) SetAiSummary(v string) {
	o.AiSummary = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FraudCheckResponse) SetMessage(v string) {
	o.Message = &v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value if set, zero value otherwise.
func (o *FraudCheckResponse) GetProcessingTimeMs() int32 {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		var ret int32
		return ret
	}
	return *o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraudCheckResponse) GetProcessingTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		return nil, false
	}
	return o.ProcessingTimeMs, true
}

// HasProcessingTimeMs returns a boolean if a field has been set.
func (o *FraudCheckResponse) HasProcessingTimeMs() bool {
	if o != nil && !IsNil(o.ProcessingTimeMs) {
		return true
	}

	return false
}

// SetProcessingTimeMs gets a reference to the given int32 and assigns it to the ProcessingTimeMs field.
func (o *FraudCheckResponse) SetProcessingTimeMs(v int32) {
	o.ProcessingTimeMs = &v
}

func (o FraudCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FraudCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["risk_score"] = o.RiskScore
	toSerialize["risk_level"] = o.RiskLevel
	if !IsNil(o.Reasons) {
		toSerialize["reasons"] = o.Reasons
	}
	if !IsNil(o.AiTriggered) {
		toSerialize["ai_triggered"] = o.AiTriggered
	}
	if !IsNil(o.AiConfidence) {
		toSerialize["ai_confidence"] = o.AiConfidence
	}
	if !IsNil(o.AiRecommendation) {
		toSerialize["ai_recommendation"] = o.AiRecommendation
	}
	if !IsNil(o.AiFraudProbability) {
		toSerialize["ai_fraud_probability"] = o.AiFraudProbability
	}
	if !IsNil(o.AiSummary) {
		toSerialize["ai_summary"] = o.AiSummary
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ProcessingTimeMs) {
		toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	}
	return toSerialize, nil
}

func (o *FraudCheckResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction_id",
		"risk_score",
		"risk_level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFraudCheckResponse := _FraudCheckResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFraudCheckResponse)

	if err != nil {
		return err
	}

	*o = FraudCheckResponse(varFraudCheckResponse)

	return err
}

type NullableFraudCheckResponse struct {
	value *FraudCheckResponse
	isSet bool
}

func (v NullableFraudCheckResponse) Get() *FraudCheckResponse {
	return v.value
}

func (v *NullableFraudCheckResponse) Set(val *FraudCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFraudCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFraudCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFraudCheckResponse(val *FraudCheckResponse) *NullableFraudCheckResponse {
	return &NullableFraudCheckResponse{value: val, isSet: true}
}

func (v NullableFraudCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFraudCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


