/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnalyzeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyzeResponse{}

// AnalyzeResponse struct for AnalyzeResponse
type AnalyzeResponse struct {
	// Whether analysis succeeded
	Success bool `json:"success"`
	// Whether a face was found
	FaceDetected bool `json:"face_detected"`
	// 128-dimensional face embedding vector (if face detected)
	Embedding []float32 `json:"embedding,omitempty"`
	// Overall quality score (0-1)
	QualityScore *float32 `json:"quality_score,omitempty"`
	// Normalized sharpness score (0-1)
	Sharpness *float32 `json:"sharpness,omitempty"`
	// Normalized brightness score (0-1)
	Brightness *float32 `json:"brightness,omitempty"`
	// Face area relative to image (0-1)
	FaceSizeRatio *float32 `json:"face_size_ratio,omitempty"`
	// List of quality warnings (e.g., \"too_dark\", \"too_blurry\")
	Warnings []string `json:"warnings,omitempty"`
	// Request processing time in milliseconds
	ProcessingTimeMs *int32 `json:"processing_time_ms,omitempty"`
	// Error message if success=false
	Error *string `json:"error,omitempty"`
}

type _AnalyzeResponse AnalyzeResponse

// NewAnalyzeResponse instantiates a new AnalyzeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyzeResponse(success bool, faceDetected bool) *AnalyzeResponse {
	this := AnalyzeResponse{}
	this.Success = success
	this.FaceDetected = faceDetected
	return &this
}

// NewAnalyzeResponseWithDefaults instantiates a new AnalyzeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyzeResponseWithDefaults() *AnalyzeResponse {
	this := AnalyzeResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *AnalyzeResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *AnalyzeResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetFaceDetected returns the FaceDetected field value
func (o *AnalyzeResponse) GetFaceDetected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FaceDetected
}

// GetFaceDetectedOk returns a tuple with the FaceDetected field value
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetFaceDetectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FaceDetected, true
}

// SetFaceDetected sets field value
func (o *AnalyzeResponse) SetFaceDetected(v bool) {
	o.FaceDetected = v
}

// GetEmbedding returns the Embedding field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetEmbedding() []float32 {
	if o == nil || IsNil(o.Embedding) {
		var ret []float32
		return ret
	}
	return o.Embedding
}

// GetEmbeddingOk returns a tuple with the Embedding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetEmbeddingOk() ([]float32, bool) {
	if o == nil || IsNil(o.Embedding) {
		return nil, false
	}
	return o.Embedding, true
}

// HasEmbedding returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasEmbedding() bool {
	if o != nil && !IsNil(o.Embedding) {
		return true
	}

	return false
}

// SetEmbedding gets a reference to the given []float32 and assigns it to the Embedding field.
func (o *AnalyzeResponse) SetEmbedding(v []float32) {
	o.Embedding = v
}

// GetQualityScore returns the QualityScore field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetQualityScore() float32 {
	if o == nil || IsNil(o.QualityScore) {
		var ret float32
		return ret
	}
	return *o.QualityScore
}

// GetQualityScoreOk returns a tuple with the QualityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetQualityScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.QualityScore) {
		return nil, false
	}
	return o.QualityScore, true
}

// HasQualityScore returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasQualityScore() bool {
	if o != nil && !IsNil(o.QualityScore) {
		return true
	}

	return false
}

// SetQualityScore gets a reference to the given float32 and assigns it to the QualityScore field.
func (o *AnalyzeResponse) SetQualityScore(v float32) {
	o.QualityScore = &v
}

// GetSharpness returns the Sharpness field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetSharpness() float32 {
	if o == nil || IsNil(o.Sharpness) {
		var ret float32
		return ret
	}
	return *o.Sharpness
}

// GetSharpnessOk returns a tuple with the Sharpness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetSharpnessOk() (*float32, bool) {
	if o == nil || IsNil(o.Sharpness) {
		return nil, false
	}
	return o.Sharpness, true
}

// HasSharpness returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasSharpness() bool {
	if o != nil && !IsNil(o.Sharpness) {
		return true
	}

	return false
}

// SetSharpness gets a reference to the given float32 and assigns it to the Sharpness field.
func (o *AnalyzeResponse) SetSharpness(v float32) {
	o.Sharpness = &v
}

// GetBrightness returns the Brightness field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetBrightness() float32 {
	if o == nil || IsNil(o.Brightness) {
		var ret float32
		return ret
	}
	return *o.Brightness
}

// GetBrightnessOk returns a tuple with the Brightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetBrightnessOk() (*float32, bool) {
	if o == nil || IsNil(o.Brightness) {
		return nil, false
	}
	return o.Brightness, true
}

// HasBrightness returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasBrightness() bool {
	if o != nil && !IsNil(o.Brightness) {
		return true
	}

	return false
}

// SetBrightness gets a reference to the given float32 and assigns it to the Brightness field.
func (o *AnalyzeResponse) SetBrightness(v float32) {
	o.Brightness = &v
}

// GetFaceSizeRatio returns the FaceSizeRatio field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetFaceSizeRatio() float32 {
	if o == nil || IsNil(o.FaceSizeRatio) {
		var ret float32
		return ret
	}
	return *o.FaceSizeRatio
}

// GetFaceSizeRatioOk returns a tuple with the FaceSizeRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetFaceSizeRatioOk() (*float32, bool) {
	if o == nil || IsNil(o.FaceSizeRatio) {
		return nil, false
	}
	return o.FaceSizeRatio, true
}

// HasFaceSizeRatio returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasFaceSizeRatio() bool {
	if o != nil && !IsNil(o.FaceSizeRatio) {
		return true
	}

	return false
}

// SetFaceSizeRatio gets a reference to the given float32 and assigns it to the FaceSizeRatio field.
func (o *AnalyzeResponse) SetFaceSizeRatio(v float32) {
	o.FaceSizeRatio = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *AnalyzeResponse) SetWarnings(v []string) {
	o.Warnings = v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetProcessingTimeMs() int32 {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		var ret int32
		return ret
	}
	return *o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetProcessingTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		return nil, false
	}
	return o.ProcessingTimeMs, true
}

// HasProcessingTimeMs returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasProcessingTimeMs() bool {
	if o != nil && !IsNil(o.ProcessingTimeMs) {
		return true
	}

	return false
}

// SetProcessingTimeMs gets a reference to the given int32 and assigns it to the ProcessingTimeMs field.
func (o *AnalyzeResponse) SetProcessingTimeMs(v int32) {
	o.ProcessingTimeMs = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AnalyzeResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyzeResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AnalyzeResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AnalyzeResponse) SetError(v string) {
	o.Error = &v
}

func (o AnalyzeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyzeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["face_detected"] = o.FaceDetected
	if !IsNil(o.Embedding) {
		toSerialize["embedding"] = o.Embedding
	}
	if !IsNil(o.QualityScore) {
		toSerialize["quality_score"] = o.QualityScore
	}
	if !IsNil(o.Sharpness) {
		toSerialize["sharpness"] = o.Sharpness
	}
	if !IsNil(o.Brightness) {
		toSerialize["brightness"] = o.Brightness
	}
	if !IsNil(o.FaceSizeRatio) {
		toSerialize["face_size_ratio"] = o.FaceSizeRatio
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	if !IsNil(o.ProcessingTimeMs) {
		toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *AnalyzeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"face_detected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnalyzeResponse := _AnalyzeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnalyzeResponse)

	if err != nil {
		return err
	}

	*o = AnalyzeResponse(varAnalyzeResponse)

	return err
}

type NullableAnalyzeResponse struct {
	value *AnalyzeResponse
	isSet bool
}

func (v NullableAnalyzeResponse) Get() *AnalyzeResponse {
	return v.value
}

func (v *NullableAnalyzeResponse) Set(val *AnalyzeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyzeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyzeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyzeResponse(val *AnalyzeResponse) *NullableAnalyzeResponse {
	return &NullableAnalyzeResponse{value: val, isSet: true}
}

func (v NullableAnalyzeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyzeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


