/*
Asguard API

Complete Asguard platform SDK - Fraud Detection + Face Verification. Two independent microservices, one unified client. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package asguard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompareResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompareResponse{}

// CompareResponse struct for CompareResponse
type CompareResponse struct {
	Success bool `json:"success"`
	// Whether faces match (distance < threshold_used)
	Match bool `json:"match"`
	// Match confidence score (0-1)
	Confidence float32 `json:"confidence"`
	// Euclidean distance between embeddings
	Distance float32 `json:"distance"`
	// The distance threshold used for this comparison
	ThresholdUsed float32 `json:"threshold_used"`
	// Quality score of the probe image (0-1)
	ProbeQuality *float32 `json:"probe_quality,omitempty"`
	ProcessingTimeMs *int32 `json:"processing_time_ms,omitempty"`
	Error *string `json:"error,omitempty"`
}

type _CompareResponse CompareResponse

// NewCompareResponse instantiates a new CompareResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompareResponse(success bool, match bool, confidence float32, distance float32, thresholdUsed float32) *CompareResponse {
	this := CompareResponse{}
	this.Success = success
	this.Match = match
	this.Confidence = confidence
	this.Distance = distance
	this.ThresholdUsed = thresholdUsed
	return &this
}

// NewCompareResponseWithDefaults instantiates a new CompareResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompareResponseWithDefaults() *CompareResponse {
	this := CompareResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *CompareResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *CompareResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMatch returns the Match field value
func (o *CompareResponse) GetMatch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Match
}

// GetMatchOk returns a tuple with the Match field value
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetMatchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Match, true
}

// SetMatch sets field value
func (o *CompareResponse) SetMatch(v bool) {
	o.Match = v
}

// GetConfidence returns the Confidence field value
func (o *CompareResponse) GetConfidence() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetConfidenceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *CompareResponse) SetConfidence(v float32) {
	o.Confidence = v
}

// GetDistance returns the Distance field value
func (o *CompareResponse) GetDistance() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetDistanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Distance, true
}

// SetDistance sets field value
func (o *CompareResponse) SetDistance(v float32) {
	o.Distance = v
}

// GetThresholdUsed returns the ThresholdUsed field value
func (o *CompareResponse) GetThresholdUsed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ThresholdUsed
}

// GetThresholdUsedOk returns a tuple with the ThresholdUsed field value
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetThresholdUsedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdUsed, true
}

// SetThresholdUsed sets field value
func (o *CompareResponse) SetThresholdUsed(v float32) {
	o.ThresholdUsed = v
}

// GetProbeQuality returns the ProbeQuality field value if set, zero value otherwise.
func (o *CompareResponse) GetProbeQuality() float32 {
	if o == nil || IsNil(o.ProbeQuality) {
		var ret float32
		return ret
	}
	return *o.ProbeQuality
}

// GetProbeQualityOk returns a tuple with the ProbeQuality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetProbeQualityOk() (*float32, bool) {
	if o == nil || IsNil(o.ProbeQuality) {
		return nil, false
	}
	return o.ProbeQuality, true
}

// HasProbeQuality returns a boolean if a field has been set.
func (o *CompareResponse) HasProbeQuality() bool {
	if o != nil && !IsNil(o.ProbeQuality) {
		return true
	}

	return false
}

// SetProbeQuality gets a reference to the given float32 and assigns it to the ProbeQuality field.
func (o *CompareResponse) SetProbeQuality(v float32) {
	o.ProbeQuality = &v
}

// GetProcessingTimeMs returns the ProcessingTimeMs field value if set, zero value otherwise.
func (o *CompareResponse) GetProcessingTimeMs() int32 {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		var ret int32
		return ret
	}
	return *o.ProcessingTimeMs
}

// GetProcessingTimeMsOk returns a tuple with the ProcessingTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetProcessingTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessingTimeMs) {
		return nil, false
	}
	return o.ProcessingTimeMs, true
}

// HasProcessingTimeMs returns a boolean if a field has been set.
func (o *CompareResponse) HasProcessingTimeMs() bool {
	if o != nil && !IsNil(o.ProcessingTimeMs) {
		return true
	}

	return false
}

// SetProcessingTimeMs gets a reference to the given int32 and assigns it to the ProcessingTimeMs field.
func (o *CompareResponse) SetProcessingTimeMs(v int32) {
	o.ProcessingTimeMs = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CompareResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompareResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CompareResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CompareResponse) SetError(v string) {
	o.Error = &v
}

func (o CompareResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompareResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["match"] = o.Match
	toSerialize["confidence"] = o.Confidence
	toSerialize["distance"] = o.Distance
	toSerialize["threshold_used"] = o.ThresholdUsed
	if !IsNil(o.ProbeQuality) {
		toSerialize["probe_quality"] = o.ProbeQuality
	}
	if !IsNil(o.ProcessingTimeMs) {
		toSerialize["processing_time_ms"] = o.ProcessingTimeMs
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *CompareResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"match",
		"confidence",
		"distance",
		"threshold_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompareResponse := _CompareResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompareResponse)

	if err != nil {
		return err
	}

	*o = CompareResponse(varCompareResponse)

	return err
}

type NullableCompareResponse struct {
	value *CompareResponse
	isSet bool
}

func (v NullableCompareResponse) Get() *CompareResponse {
	return v.value
}

func (v *NullableCompareResponse) Set(val *CompareResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompareResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompareResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompareResponse(val *CompareResponse) *NullableCompareResponse {
	return &NullableCompareResponse{value: val, isSet: true}
}

func (v NullableCompareResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompareResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


